FROM ubuntu:latest as build

RUN apt-get update
RUN apt-get install openjdk-17-jdk -y
COPY . .

RUN apt-get install -y maven
RUN mvn clean install

FROM openjdk:21-jdk-slim

EXPOSE 8080


COPY --from=build /build/target/pactosolucoes-1.0.0.jar pactosolucoes.jar

ENTRYPOINT [ "java", "-jar", "app.jar" ]
